# Generated by Django 4.1.7 on 2023-08-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parcelas',
            new_name='Parcela',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
