# Generated by Django 4.1.7 on 2023-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdor', '0005_remove_sun_full_shadow_remove_sun_full_sun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sun',
            name='sun',
            field=models.CharField(default='sun', max_length=25, verbose_name='SunOrShadow'),
        ),
    ]
