# Generated by Django 4.1.7 on 2023-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdor', '0007_person_parcela_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
