# Generated by Django 4.1.7 on 2023-08-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdor', '0010_remove_parcela_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdor.group'),
        ),
    ]
