# Generated by Django 4.1.7 on 2023-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdor', '0011_parcela_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='plot_users',
        ),
        migrations.AlterField(
            model_name='parcela',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plot Length'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
